"""Snakemake pipeline for testing redundans params"""
from plumbum import local

IDENTITY = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 0.98]

rule all:
    expand("output/busco/FASC.{id}/short_summary_FASC.txt", ident=IDENTITY)

rule redundans:
    output:
        fasta = 'output/redundans/FASC.{id}.fasta',
        index = 'output/redundans/FASC.{id}.1.bt2'
    params:
        output_prefix = 'output/redundans/FASC.{id}'
    log:
        'output/redundans/log/FASC.{id}.log'
    run:
        shell('python2 util/redundans/redundans.py -v -f input/FASC.fasta '
              '-i input/FASC.R1.fastq.gz input/FASC.R2.fastq.gz '
              '-o {params.output_prefix} --nogapclosing --noscaffolding '
              '--identity {wildcards.id} 2> {log}')

rule busco:
    input: 'output/redundans/FASC.{id}.fasta'
    output: 'output/busco/FASC.{id}/short_summary_FASC.txt'
    threads: 8
    params:
        outdir = 'output/busco/FASC.{id}',
        output_prefix = 'FASC.{id}'
    script: 'scripts/busco.py'


        
