---
# Snakemake config
isolates: all
readsdir: input/reads
adapters: input/adapters/adapters_illumina.fa
blast_database: input/blast_database/nt
nodes_dmp: input/taxonomy/nodes.dmp
names_dmp: input/taxonomy/names.dmp
